export const RESET_ALL = "RESET_ALL";
export const PLAY_PAUSE = "PLAY_PAUSE";
export const START_TIMER = "START_TIMER";
export const INCREASE_VALUE = "INCREASE_VALUE";
export const DECREASE_VALUE = "DECREASE_VALUE";
export const TOGGLE_TIMER_LABEL = "TOGGLE_TIMER_LABEL";